CC=clang++
CFLAGS=-std=c++11 -Wall 
INC=-I/usr/local/include/opencv -I/usr/local/include -I/usr/local/include/dcmtk/**
LDFLAGS=-L/usr/local/lib -L/usr/local/lib/dcmtk -L/usr/lib -lz -lpthread -ldcmjpeg -lijg8 -lijg12 -lijg16 -ldcmimage -ldcmimgle -ldcmdsig -ldcmsr -ldcmtls -ldcmnet -ldcmdata -li2d -loflog -lofstd -lopencv_calib3d -lopencv_core -lopencv_features2d -lopencv_flann -lopencv_highgui -lopencv_imgcodecs -lopencv_imgproc -lopencv_ml -lopencv_objdetect -lopencv_photo -lopencv_shape -lopencv_stitching -lopencv_superres -lopencv_ts -lopencv_video -lopencv_videoio -lopencv_videostab -lgsl -lgslcblas 
DFLAGS=-DHAVE_CONFIG_H
SRCS=breast.cpp breastgradient_segmented.cpp mammography.cpp breast_dist.cpp dailyCalibration.cpp PhantomCalibration.cpp scanner.cpp breastgradient.cpp main.cpp various.cpp
OBJS= main.o various.o scanner.o PhantomCalibration.o mammography.o dailyCalibration.o breast.o
PROG= main
$(PROG): $(OBJS) 
	$(CC) $(CFLAGS) $(DFLAGS) -o $(PROG) $(OBJS) $(LDFLAGS)
.cpp.o:
	$(CC) $(CFLAGS) $(DFLAGS) -c $*.cpp 
clean:
	rm $(OBJS) $(PROG)
depend:
	makedepend -- $(CFLAGS) -- $(SRCS)
# DO NOT DELETE
